# Generated by Django 5.2 on 2026-09-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=100)),
                ('ville', models.CharField(default='Dakar', max_length=50)),
                ('salaire', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('contrat', models.CharField(choices=[('CDI', 'Contrat à durée indeterminée'), ('CDI', 'Contrat à durée eterminée'), ('STAGE', 'Contrat de stage'), ('PRESTATION', 'Contrat de prestation')], default='PRESTATION', max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
