# Generated by Django 5.2 on 2026-09-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_entreprise_remove_offre_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='teletravail',
            field=models.BooleanField(default=False),
        ),
    ]
