# Generated by Django 5.2 on 2026-09-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0003_offre_teletravail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='entreprise',
            new_name='name',
        ),
    ]
