# Generated by Django 5.2 on 2026-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0004_rename_entreprise_entreprise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
